# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{precssious}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Erik Hansson"]
  s.date = %q{2009-09-09}
  s.default_executable = %q{precssious}
  s.description = %q{}
  s.email = %q{erik@bits2life.com}
  s.executables = ["precssious"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/precssious",
     "lib/precssious.rb",
     "lib/precssious/preprocessor.rb",
     "lib/precssious/rails/controller.rb",
     "lib/precssious/rails/routes.rb",
     "lib/precssious/rule.rb",
     "lib/precssious/token.rb",
     "lib/precssious/value.rb",
     "lib/tasks/precssious.rb",
     "precssious.gemspec",
     "spec/precssious_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/erikhansson/precssious}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Merges CSS files and allows nested declarations}
  s.test_files = [
    "spec/precssious_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
